version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"   # NATS default port
      - "8222:8222"   # Monitoring port (optional)
    command: ["-js"]  # Enables JetStream (optional)
